version: '3'
services:
  redis:
    image: redis
    ports:
      - 127.0.0.1:25091:6379
    volumes:
      - 'redis_data:/data'
    command: redis-server --appendonly yes
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - 127.0.0.1:2181:2181
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - 127.0.0.1:25092:9092
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper
volumes:
  redis_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
